### ISSUE TITLE
Remove unnecessary issue templates

### ISSUE THREAD

**Issue by modir** [MithrilJS/docs#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Offending URL

https://github.com/MithrilJS/docs/

### Issue description

There is no need for all these issue templates in the docs repo:

![Screenshot from 2024-09-23 14-50-00](https://github.com/user-attachments/assets/865af593-13d4-47ba-9f76-3389da6aac7c)

**Comment by dead-claudia** [comment]
Removed the feature request link in https://github.com/MithrilJS/docs/commit/861d4669a3dfd90e7422355735c9db5ba2cdf858 since I don't expect significant feature requests to be all that common here, but the rest is there on purpose. Most docs questions in my experience fall into one of three categories:

1. People missing small specifics that are already documented
2. People not entirely sure what they're asking
3. A mixture of 1 and 2

The formats of the discussion board and Zulip are better suited for these. While it's possible to work through them as issues, it's not very efficient. Zulip offers a place for live discussion (which GH Issues can't really accommodate), and the discussion board's threads feature helps isolate tangents from the main discussion better.
